# Generated by Django 2.1.10 on 2019-07-03 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=5)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('numerator', models.PositiveIntegerField()),
                ('denominator', models.PositiveIntegerField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sector', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='regions.Block')),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panchayat', to='regions.Panchayat')),
            ],
        ),
    ]
