# Generated by Django 2.1 on 2019-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='percent',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
