# Generated by Django 2.1 on 2019-07-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='block',
            name='lng',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=8),
        ),
    ]
